title: Дижитал соёлд суралцацгаая
description: Шинжлэх Ухаан Технологийн Их Сургуулийн мэдээ
baseurl: "/must-dx-news"
url: "https://ubayarbat.github.io"

theme: just-the-docs

# Хайлт идэвхжүүлэх
search_enabled: true

# Footer
footer_content: "© 2026 MUST"

# Өнгөний схем
color_scheme: light

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
